[package]
name = "rusty-cutter"
version = "0.1.0"
edition = "2021"
default-run = "rcut"

[[bin]]
name = "rcut"
path = "src/main.rs"

[dependencies]
clap = { version = "4.5.16", features = ["derive"] }
regex = "1.10.6"

